# Intro to Bayesian Statistics Lab

Complete the following set of exercises to solidify your knowledge of Bayesian statistics and Bayesian data analysis.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## 1. Cookie Problem

Suppose we have two bowls of cookies. Bowl 1 contains 30 vanilla cookies and 10 chocolate cookies. Bowl 2 contains 20 of each. You randomly pick one cookie out of one of the bowls, and it is vanilla. Use Bayes Theorem to calculate the probability that the vanilla cookie you picked came from Bowl 1?

In [2]:
priors=[0.5,0.5]

In [3]:
likelihoods = [0.75, 0.5]

In [4]:
def bayes_rule(priors, likelihoods):
    marg = sum(np.multiply(priors, likelihoods))
    post = np.divide(np.multiply(priors, likelihoods), marg)
    return post

In [5]:
bayes_rule(priors, likelihoods)

array([0.6, 0.4])

In [6]:
#La probabilidad de que la galleta de vainilla viene del Bowl #1 es 60%.

What is the probability that it came from Bowl 2?

In [7]:
#La probabilidad de que la galleta de vainilla viene del Bowl #2 es 40%.

What if the cookie you had picked was chocolate? What are the probabilities that the chocolate cookie came from Bowl 1 and Bowl 2 respectively?

In [8]:
likelihoods = [0.25, 0.5]

In [9]:
def bayes_rule(priors, likelihoods):
    marg = sum(np.multiply(priors, likelihoods))
    post = np.divide(np.multiply(priors, likelihoods), marg)
    return post

In [10]:
bayes_rule(priors, likelihoods)

array([0.33333333, 0.66666667])

In [11]:
#La probabilidad de que la galleta de chocolate viene del Bowl #1 es 33.33%.

In [12]:
#La probabilidad de que la galleta de chocolate viene del Bowl #2 es 66.67%.

## 2. Candy Problem

Suppose you have two bags of candies:

- In Bag 1, the mix of colors is:
    - Brown - 30%
    - Yellow - 20%
    - Red - 20%
    - Green - 10%
    - Orange - 10%
    - Tan - 10%
    
- In Bag 2, the mix of colors is:
    - Blue - 24%
    - Green - 20%
    - Orange - 16%
    - Yellow - 14%
    - Red - 13%
    - Brown - 13%
    
Not knowing which bag is which, you randomly draw one candy from each bag. One is yellow and one is green. What is the probability that the yellow one came from the Bag 1?

*Hint: For the likelihoods, you will need to multiply the probabilities of drawing yellow from one bag and green from the other bag and vice versa.*

In [13]:
priors=[0.5,0.5]

In [14]:
likelihoods=[0.2*0.2,0.1*0.14]

In [15]:
def bayes_rule(priors, likelihoods):
    marg = sum(np.multiply(priors, likelihoods))
    post = np.divide(np.multiply(priors, likelihoods), marg)
    return post

In [16]:
bayes_rule(priors, likelihoods)

array([0.74074074, 0.25925926])

In [17]:
#La probabilidad de que el dulce amarillo viene de la bolsa 1 es de 74.07%

What is the probability that the yellow candy came from Bag 2?

In [18]:
#La probabilidad de que el dulce amarillo viene de la bolsa 2 es de 25.93%

What are the probabilities that the green one came from Bag 1 and Bag 2 respectively?

In [19]:
likelihoods=[0.1*0.14,0.2*0.2]

In [20]:
def bayes_rule(priors, likelihoods):
    marg = sum(np.multiply(priors, likelihoods))
    post = np.divide(np.multiply(priors, likelihoods), marg)
    return post

In [21]:
bayes_rule(priors, likelihoods)

array([0.25925926, 0.74074074])

In [22]:
#La probabilidad de que el dulce verde viene de la bolsa 1 es de 25.93%

In [23]:
#La probabilidad de que el dulce verde viene de la bolsa 2 es de 74.07%

## 3. Monty Hall Problem

Suppose you are a contestant on the popular game show *Let's Make a Deal*. The host of the show (Monty Hall) presents you with three doors - Door A, Door B, and Door C. He tells you that there is a sports car behind one of them and if you choose the correct one, you win the car!

You select Door A, but then Monty makes things a little more interesting. He opens Door B to reveal that there is no sports car behind it and asks you if you would like to stick with your choice of Door A or switch your choice to Door C. Given this new information, what are the probabilities of you winning the car if you stick with Door A versus if you switch to Door C?

In [24]:
priors=[0.33,0.33,0.33]

In [25]:
likelihoods = [0.5,0,0.5]

In [26]:
def bayes_rule(priors, likelihoods):
    marg = sum(np.multiply(priors, likelihoods))
    post = np.divide(np.multiply(priors, likelihoods), marg)
    return post

In [27]:
bayes_rule(priors, likelihoods)

array([0.5, 0. , 0.5])

In [28]:
#La probabilidad de ganar el carro es de 50%.

## 4. Bayesian Analysis 

Suppose you work for a landscaping company, and they want to advertise their service online. They create an ad and sit back waiting for the money to roll in. On the first day, the ad sends 100 visitors to the site and 14 of them sign up for landscaping services. Create a generative model to come up with the posterior distribution and produce a visualization of what the posterior distribution would look like given the observed data.

In [29]:
#To set this up in Python, we are going to use Numpy to generate a uniform distribution from 100,000 random draws of numbers between 0 and 1.
n_draws = 100000
prior = pd.Series(np.random.uniform(0, 1, size=n_draws))

Produce a set of descriptive statistics for the posterior distribution.

In [30]:
observed=14

In [31]:
def generative_model(param):
    result = np.random.binomial(100, param)
    return result

In [32]:
sim_data = list()

for p in prior:
    sim_data.append(generative_model(p))

In [33]:
posterior = prior[list(map(lambda x: x == observed, sim_data))]

In [34]:
posterior.describe()

count    976.000000
mean       0.147130
std        0.034833
min        0.052471
25%        0.123272
50%        0.145284
75%        0.168648
max        0.301333
dtype: float64

What is the 90% credible interval range?

In [35]:
print(posterior.quantile(.025), '|', posterior.quantile(.975))

0.08812190831661684 | 0.22033040121899386


What is the Maximum Likelihood Estimate?

In [36]:
rounded = posterior.round(2)
mode = rounded.mode()[0]
probability = list(rounded).count(mode)/len(rounded)
print('Maximum Likelihood Estimate: ', mode, '|',probability)

Maximum Likelihood Estimate:  0.13 | 0.12397540983606557
